In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### index and slicing

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8] = -5
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [21]:
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
slicingDizisi = baskaDizi[4:9]
slicingDizisi

array([4, 5, 6, 7, 8])

In [25]:
slicingDizisi[:] = 700
slicingDizisi

array([700, 700, 700, 700, 700])

In [27]:
baskaDizi # slicingDizisi içinde yaptığımız değişiklik baskaDizi içinde de görülür.

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Orjinali değişmesin diyorsak 

In [28]:
ornekDizi = np.arange(0,24)

In [29]:
ornekDiziKopyası = ornekDizi.copy()

In [30]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
ornekDiziKopyaSlicing = ornekDiziKopyası[3:6]
ornekDiziKopyaSlicing[:] = 800
ornekDiziKopyaSlicing

array([800, 800, 800])

In [35]:
ornekDiziKopyası 

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [36]:
ornekDizi # orjinal dizide herhangi bir değişiklik yapmak istemiyorsak kopyaasını alıyoruz. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Şimdiye kadar tek boyutlu dizilerde çalıştık.

## matrix 2D

In [37]:
benimListem = [[10,20,30], [20,30,40], [40,50,60]]


In [39]:
benimMatrixDizim = np.array(benimListem)
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [40]:
benimMatrixDizim[0]

array([10, 20, 30])

In [41]:
benimMatrixDizim[1][2]

40

In [43]:
benimMatrixDizim[1,2] # row da 1. indeks coloumn da 2. indeks

40

In [45]:
benimMatrixDizim[0:, 2]

array([30, 40, 60])

In [46]:
benimMatrixDizim[0:, 1]

array([20, 30, 50])

In [47]:
benimMatrixDizim[0:, 0]

array([10, 20, 40])

In [58]:
yeniListe = [list(range(5)), list(range(5,10)), list(range(10,15)), list(range(15,20)), list(range(20,25))]
yeniListe

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [59]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
yeniMatrix[[0, 2, 4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [61]:
yeniMatrix[[4, 2, 0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

### Operations

In [64]:
yeniBirDizi = np.random.randint(1,100,20)

In [65]:
yeniBirDizi

array([11, 50, 27, 69, 98, 79, 70, 85, 24,  9, 28, 41, 56, 59, 35, 23,  5,
        7, 78, 41])

In [66]:
yeniBirDizi > 24

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False, False, False,
        True,  True])

In [68]:
sonucDizisi = yeniBirDizi > 24
sonucDizisi

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False, False, False,
        True,  True])

In [69]:
yeniBirDizi

array([11, 50, 27, 69, 98, 79, 70, 85, 24,  9, 28, 41, 56, 59, 35, 23,  5,
        7, 78, 41])

In [71]:
yeniBirDizi[sonucDizisi]

array([50, 27, 69, 98, 79, 70, 85, 28, 41, 56, 59, 35, 78, 41])

In [72]:
yeniBirDizi[yeniBirDizi > 24]

array([50, 27, 69, 98, 79, 70, 85, 28, 41, 56, 59, 35, 78, 41])

In [74]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [76]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [77]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [78]:
sonDizi / sonDizi

C:\Users\hp\AppData\Local\Temp\ipykernel_14084\1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [81]:
np.max(sonDizi)

23

In [82]:
np.min(sonDizi)

0

In [83]:
np.argmax(sonDizi)

23