In [1]:
import numpy as np

In [7]:
benimListem = [20, 30, 40]
benimListem

[20, 30, 40]

# array

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
type(np.array(benimListem))

numpy.ndarray

In [5]:
matrixListesi = [[10,20,30], [20,30,40], [30,40,50]]

In [6]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

### arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros

In [11]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [14]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace

In [15]:
 np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [17]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [18]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [21]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

### eye

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

#### randn

In [53]:
np.random.randn(4) # tek boyutlu float değerler

array([ 0.46260777,  0.39325176, -0.45042854, -0.71890756])

In [26]:
np.random.randn(4,4) # 2D

array([[ 2.73167016,  1.46837518,  2.29064083,  0.78649414],
       [ 0.88951599, -0.41659389,  2.07502772, -0.70931718],
       [-0.37752041,  1.53922028, -0.50096076, -1.06484288],
       [ 1.22333907,  0.86203615,  0.83047142,  0.37892191]])

#### randint

In [27]:
np.random.randint(1,10) # integer değer döndürür. stop değeri dönmez.

1

In [31]:
np.random.randint(1,300,5)

array([ 16,  39, 205, 213, 209])

In [33]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
benimRandomDizim = np.random.randint(0,100,30)
benimRandomDizim

array([86, 25, 66,  4, 41, 42,  8, 26, 26, 76, 59, 95, 65, 54, 49, 74, 12,
        2, 81,  9, 14, 64, 63, 86, 59, 80, 42, 12, 42, 62])

##  Numpy Dizilerin Metotları

In [39]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### reshape

In [37]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
benimNumpyDizim.reshape(6,5) # yeniden şekillendir. 5 erli 6 grup yap.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### shape

In [49]:
benimNumpyDizim.shape

(30,)

In [51]:
reshapeDizim = benimNumpyDizim.reshape(6,5)
reshapeDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
reshapeDizim.shape # güncel dizimin hangi şekle sahip olduğunu gösterir.

(6, 5)

### max - min

In [40]:
benimNumpyDizim.max()

29

In [41]:
benimRandomDizim = np.random.randint(0,100,30)
benimRandomDizim

array([97, 80, 74, 57, 84, 32, 74,  0, 25, 27, 84, 29, 77, 44, 61, 84, 84,
       40, 89,  1, 40, 99, 72, 58,  0, 35, 73, 70,  8, 42])

In [42]:
benimRandomDizim.max()

99

In [43]:
benimRandomDizim.min()

0

### argmax - argmin

In [44]:
benimRandomDizim.argmax() # indeksini aramak için kullanıyoruz

21

In [45]:
benimRandomDizim.argmin()

7